### ISSUE TITLE
[core] Object data is empty after HMR (Hot Module Replacement) reload

### ISSUE THREAD

**Issue by Zehir** [prazdevs/pinia-plugin-persistedstate#79] opened 2022-06-21 20:27 UTC
Hi, it's a quite specific case but there is my issue;

More info on [HMR here](https://pinia.vuejs.org/cookbook/hot-module-replacement.html).
### Context
I started with the [vitesse template](https://github.com/antfu/vitesse) from github.

You can chekout [this commit](https://github.com/Zehir/deconz-ruler/commit/a2427fd3a328794c2f9e3efb7bed197d421188cb) if you wan't to try on your side.

I have a store defined like this :
```typescript
import { acceptHMRUpdate, defineStore } from 'pinia'
export const useGatewaysStore = defineStore('gateways', () => {
  const data_array = ref<any[]>([])
  // data_array.value[0] = 3

  const data_record = reactive({})
  // data_record.foo = 35

  const test = computed(() => 1)

  return { data_array, data_record, test }
}, {
  // https://github.com/prazdevs/pinia-plugin-persistedstate
  persist: {
    paths: [
      'data_array',
      'data_record',
    ],
  },
})

// https://pinia.vuejs.org/cookbook/hot-module-replacement.html
if (import.meta.hot)
  import.meta.hot.accept(acceptHMRUpdate(useGatewaysStore, import.meta.hot))
```

With this data in the store : 
```json
{
  "data_array": [1],
  "data_record": {"foo":{"foo":38}}
}
```

### Issue
When I load the page I get the correct value from the store.
When I edit the store vite is sending the update to the browser to reload the store. For example if I edit the value of the computed property, it's updated in the browser.
The `data_array` still contain the data but `data_record` became empty.

With manual defined values (the comments) without `persist` configuration, I keep the previous values and the computed value is updated. That why I think it's an issue with the plugin.

**Comment by prazdevs** [comment] 2022-07-27 22:29
Sorry this issue completely went under the radar, i'll look into it as soon as V2 is live 🙏

**Comment by Zehir** [comment] 2022-07-27 22:57
> Sorry this issue completely went under the radar, i'll look into it as soon as V2 is live 🙏 

No problem, I replaced the hot reload for à full reload for the store for now

**Comment by prazdevs** [comment] 2022-11-26 13:03
Is this issue still a thing with the latest version of pinia and the plugin ?

**Comment by Zehir** [comment] 2022-11-26 13:15
can't test for now, I will test again in a few month

**Comment by Zehir** [comment] 2023-01-17 16:51
Sorry @prazdevs for late response but it's still happening in 2.4.0
```json
{
    "@vueuse/core": "^9.11.0",
    "@vueuse/head": "^1.0.22",
    "axios": "^1.2.2",
    "binary-parser": "^2.2.1",
    "color": "^4.2.3",
    "nprogress": "^0.2.0",
    "pinia": "^2.0.29",
    "pinia-plugin-persistedstate": "^3.0.2",
    "postcss": "^8.4.21",
    "prism-theme-vars": "^0.2.4",
    "vite-plugin-vuetify": "^1.0.1",
    "vue": "^3.2.45",
    "vue-demi": "^0.13.11",
    "vue-i18n": "^9.2.2",
    "vue-json-viewer": "^3.0.4",
    "vue-router": "^4.1.6",
    "vue3-perfect-scrollbar": "^1.6.1",
    "vuetify": "^3.1.1"
}
```

Before I save :
![image](https://user-images.githubusercontent.com/845225/212960923-69a1c0e9-b997-4ba6-b66e-983ed8672208.png)

After I save :
![image](https://user-images.githubusercontent.com/845225/212961101-b30ff3d8-b833-44cb-a17e-1ecfd433b5f4.png)
No relevant log in the console.

And after I refresh the page I get the data back.

**Comment by prazdevs** [comment] 2023-01-17 17:39
Is there a commit/repo/stackblitz I can use to reproduce it with the latest version ?

**Comment by Zehir** [comment] 2023-01-17 18:56
Sure, I made a light test :
https://github.com/Zehir/deconz-ruler/commit/3fbc39fa2c3c859b55f3c9b789cfc2de7e8ebbc0

Run it by using `pnpm dev` (after a ``pnpm install`).
Open localhost:4000/demo on a browser.
Click on the button generate data.

How to reproduce :

- After a page refresh the data is still present.
- In the file `src/stores/demo.ts` comment the line `const testMethod = computed(() => 1)` and then save.
- The page reload but the state is lost.

When you remove the persist configuration I don't lose the data.
When you update the vue in `src/pages/demo.vue` I don't lose the data.

**Comment by prazdevs** [comment] 2023-02-10 21:00
So i looked a bit into it and the issue only occurs when using reactive and setup-syntax. Maybe i should look deeper into pinia HMR and try to understand why it won't work with this particular case. If you can use refs instead of reactive, it *shoud* work

**Comment by MZ-Dlovely** [comment] 2023-05-09 10:14
has it been resolved?

**Comment by MZ-Dlovely** [comment] 2023-05-09 11:46
i cant fork it.T_T

**Comment by prazdevs** [comment] 2023-05-09 19:35
I'd think the reason it refreshes is because it'd just hot-reload initial state, and not trigger the hydration from the plugin 🤔  have to find a way to trigger it on hmr i guess

**Comment by prazdevs** [comment] 2023-05-09 19:50
Ok i can get it working by changing this [line](https://github.com/vuejs/pinia/blob/971dcdbf4b825e1791d02a85d6788fa72236107c/packages/pinia/src/hmr.ts#L123) from pinia itself into `useStore(pinia, existingStore)?.$hydrate()`
But it's kinda inside pinia, gotta find a way to call $hydrate in this situation smh

**Comment by Zehir** [comment] 2023-05-09 20:55
what about creating your own acceptHMRUpdate function ?

**Comment by prazdevs** [comment] 2023-05-09 21:11
that's literally what i'm doing rn 😬 i'll probably export it in some special package to avoid polluting the main one as it's more experimental than anything

**Comment by prazdevs** [comment] 2023-05-09 21:50
Ok i have made and published `@pinia-plugin-persistedstate/hmr` that exports `acceptHMRUpdateWithHydration`.
You should just be able to replace pinia's with this one and it _should_ work. 🤔

**Comment by Zehir** [comment] 2023-05-09 22:53
Thanks I will try this when I have some time available

**Comment by MZ-Dlovely** [comment] 2023-05-10 11:20
wait for me to write its workflow

**Comment by prazdevs** [comment] 2023-05-10 11:22
🤔 i think i get it, the 2 would complement each other ?

**Comment by MZ-Dlovely** [comment] 2023-05-10 11:26
the hot store will be create and merge with old store. what we need to do is `$hydrate` after store merged

**Comment by MZ-Dlovely** [comment] 2023-05-10 11:32
if used original code will be this
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/93523064/e7608ad6-1c89-439f-b39d-2389172d24f1)
print by `afterRestore` hook

**Comment by MZ-Dlovely** [comment] 2023-05-10 11:34
when i mark debug for it
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/93523064/56d2e8a4-4f45-4830-a652-54095be2abf8)

**Comment by MZ-Dlovely** [comment] 2023-05-10 12:09
🤔 i get the best solution, maybe

**Comment by prazdevs** [comment] 2023-05-10 12:14
@MZ-Dlovely feel free to reopen a PR if that can fix this issue, would this also need the custom AcceptHMRUpdate method ?

**Comment by MZ-Dlovely** [comment] 2023-05-10 12:19
i think we need. i'm doing for it

**Comment by MZ-Dlovely** [comment] 2023-05-10 13:01
i will check it a little time

**Comment by prazdevs** [comment] 2023-05-16 18:12
Im very busy these days and wanna solve this problem properly. Need to see how HMR should be handled: 
- do we want to hydrate on hot reload with stored data
- persist new store (and initial data), and consider stored data stale
- we could even make that configurable maybe

**Comment by hi-reeve** [comment] 2023-05-26 05:25
any update on this?

**Comment by waney** [comment] 2023-05-29 08:38
Thank you. any update on this?

**Comment by prazdevs** [comment] 2023-05-29 19:17
Hi, been very busy with work and life these days. 
I wanna try to fix this for good, but I want to avoid adding much stuff to the main plugin, or risky side effects. 

There's also the concept of "what is stale data" when using HMR: the stored one? or the initial state one?

Once these questions are solved, and we can have a solution that should be good :)

**Comment by prazdevs** [comment] 2023-07-16 15:05
@MZ-Dlovely could you test HMR with the current repo if it works for you as intended ? using the default AcceptHMRUpdate function provided by pinia? 
If it works, i'll make a release :)

**Comment by MZ-Dlovely** [comment] 2023-07-20 01:20
> @MZ-Dlovely could you test HMR with the current repo if it works for you as intended ? using the default AcceptHMRUpdate function provided by pinia? If it works, i'll make a release :)

i'm sorry that i just saw your msg. have you tested for it? what should i do for it more? XD

**Comment by prazdevs** [comment] 2023-07-20 13:39
> > @MZ-Dlovely could you test HMR with the current repo if it works for you as intended ? using the default AcceptHMRUpdate function provided by pinia? If it works, i'll make a release :)
> 
> i'm sorry that i just saw your msg. have you tested for it? what should i do for it more? XD

Just take the latest commit of the repo, and try HMR the way Pinia recommends it (using their AcceptHMRUpdate function), and tell me if it behaves as you would expect it to :)

**Comment by MZ-Dlovely** [comment] 2023-07-21 03:30
> Just take the latest commit of the repo, and try HMR the way Pinia recommends it (using their AcceptHMRUpdate function), and tell me if it behaves as you would expect it to :)

i did find no bug by my tests in development mode, using pinia's `AcceptHMRUpdate`. if there is some bug arisen, tell me pls. 👍

**Comment by prazdevs** [comment] 2023-07-21 09:49
Ok then, i'll issue a release then and hopefully close this issue

**Comment by prazdevs** [comment] 2023-07-23 21:39
🎉 `3.2.0` is released. This should now be fixed and we can finally open that long running issue ! Thanks @MZ-Dlovely and everyone involved in it !

**Closed by prazdevs** 2023-07-23 21:39 UTC
Labels: 🐛 bug, ✋ help wanted
