### ISSUE TITLE
[nuxt] Cookie persistence broken on Netlify builds

### ISSUE THREAD

**Issue by fanckush** [prazdevs/pinia-plugin-persistedstate#269] opened 2024-01-12 12:49 UTC
### Describe the bug

on my local dev server cookie based persistence (default config) works fine
when I deploy the site to on netlify, I can see pinia trying to set the cookie but the name is being set to `''` blank and the value is set to `undefined`. While on the dev server the cookie name is `main` and the value is the encoded store

Dev server on localhost
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/6278713/b97e4181-5667-4d4c-a82b-460c71b1c4e4)

Netlify deploy
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/6278713/e07491d3-e498-43fc-9f9d-2d7d1697c81c)

**note: ** i'm not 100% sure that the reproduction is useful. while the bug occurs there as well, I don't know if the reason is the same. i'm happy to debug this however you suggest.

### Reproduction

https://stackblitz.com/edit/github-4dwbqx-jbccag?file=package.json,nuxt.config.ts,app.vue,composables%2Fstore.ts,package-lock.json

### System Info

```Shell
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 166.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /opt/homebrew/opt/node@20/bin/node
    npm: 10.2.4 - /opt/homebrew/opt/node@20/bin/npm
    bun: 1.0.22 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 120.1.61.116
    Safari: 17.1
```

### Used Package Manager

bun

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment] 2024-01-12 14:59
Yeah, the stackblitz you gave works perfectly fine (open the preview in a new window to have it working).
Curious to see if it's Netlify specific or some other SaaS have issues. I've had issues with Netlify building the app couple times so idk. I'll eventually take a look whenever.

Have you tried playing around using localStorage instead of cookies to see if the problem is cookies or the plugin itself ?

**Comment by prazdevs** [comment] 2024-01-12 18:18
However be mindful of using data from the store, as it will be rehydrated only when the client is hydrated as well. So data from the server is not the same as the one in the client

**Comment by fanckush** [comment] 2024-02-08 12:54
I was using `ssr: false` so far. Now that I switched to ssr, I get the hydration mismatch. Is there another storage mechanism I could use that is read by the server as well?

**Comment by prazdevs** [comment] 2024-09-04 22:05
v4 may fix your problem.

Closing this for now, feel free to reopen or create a new issue if the problem is still there

**Closed by prazdevs** 2024-09-04 22:05 UTC
Labels: ✋ help wanted
