### ISSUE TITLE
[nuxt] createNuxtPersistedState SSR states empty (not working)

### ISSUE THREAD

**Issue by stephenjason89** [prazdevs/pinia-plugin-persistedstate#97] opened 2022-08-04 12:56 UTC
### Describe the bug

The states are only restored from cookie at the client side.
Anything that is rendered on server side like,
any code that runs  on created hook or earlier doesn't have the states available
You can see it if you console.log it.
This means, middleware and plugins store will return an empty state on page load as well.

### Reproduction

Install @pinia/nuxt 0.2.0 together with pinia 2.0.15
Tested with pinia-plugin-persisted: 1.6.3 and 2.1.0
with 2.1.0 i get the following error
<img width="882" alt="image" src="https://user-images.githubusercontent.com/3810177/182853489-2535b424-2e3b-4296-b03e-beb45a06f0b9.png">
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/3810177/182853593-48118a67-044e-49fe-b12c-a8cd8dc39384.png">

### System Info

```Shell
System:
    OS: macOS 12.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 20.51 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0
    Safari: 15.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by stephenjason89** [comment] 2022-08-05 05:52
May I send a pull request that fixes this issue?
Also, this might be addressed a little bit as well https://github.com/prazdevs/pinia-plugin-persistedstate/issues/84
I placed an option to store multiple cookies to increase the 4096 bytes limit. But due note that if a lot of huge cookies are placed in the header that it will still throw an error that header is too big.

Lastly, I used https://github.com/microcipcip/cookie-universal/tree/master/packages/cookie-universal-nuxt
to persist the changes to the cookie in the client side when changes were made during SSR.

**Comment by prazdevs** [comment] 2022-08-05 11:36
Can you provide a repo or a stackblitz to reproduce the error ?

**Comment by stephenjason89** [comment] 2022-08-05 12:03
Hello @prazdevs I'll create a PR so you can see how I fixed it on my end.
Give me a moment

**Comment by stephenjason89** [comment] 2022-08-05 12:24
Hello @prazdevs 
Here's how it should look.

This is my plugin
<img width="663" alt="image" src="https://user-images.githubusercontent.com/3810177/183076352-7eb23e77-f6af-4e83-b6f3-8cc6431c6183.png">

This should be nuxt.mjs
<img width="871" alt="image" src="https://user-images.githubusercontent.com/3810177/183076508-28b69043-835c-4d19-8a9e-0eeda0ab12ba.png">

it's just throwing some errors now because of optional chaining.

**Comment by stephenjason89** [comment] 2022-08-05 12:46
Hello @prazdevs Please check https://github.com/prazdevs/pinia-plugin-persistedstate/pull/99

Though i still have a minor issue. 
Do you have discord?

**Comment by prazdevs** [comment] 2022-08-05 12:56
> Hello @prazdevs Please check #99
> 
> Though i still have a minor issue. Do you have discord?

I'm kinda busy with tons of stuff atm but i do have discord at PraZ#4184

**Comment by stephenjason89** [comment] 2022-08-05 13:02
No worries @prazdevs 
Well my question is,

I'm using this as my current nuxt plugin setup
<img width="786" alt="image" src="https://user-images.githubusercontent.com/3810177/183082317-5fc12067-52a4-4b9a-8967-132642f7877f.png">

Everything works fine. Also, I can access everything at nuxt midldleware too.
Serverside changes to cookie is being reflected to client side cookie as well.

Now, I just tried editing the node_modules file dist/nuxt.mjs
Refactored my this to work as a plugin.

Everything is working except, I can't access it inside a middleware.
Please refer to my PR and see if it's the same with you since in the PR i edited the nuxt.ts and not the mjs file.

**Comment by prazdevs** [comment] 2022-08-05 13:13
There is one problem tho, is that i do want to enforce the "0 external dependency" policy on the plugin/repo. Leaving the choice of external libs to the user. However what could be worked on are helpers to integrate these external libs into the plugin. If that makes sense

**Comment by stephenjason89** [comment] 2022-08-05 13:47
@prazdevs I understand where you're coming from. The only problem is that useCookie by nuxt doesn't work properly across server to client cookie management.

This only works properly on client only setup.

**Comment by stephenjason89** [comment] 2022-08-06 11:48
@prazdevs Now I know why in nuxt.mjs everything is not accessible inside a middleware
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/3810177/183247492-20b9ffbd-19ff-408e-95ce-971e76c37b80.png">

I just console log trying to cookie get inside the nuxt plugin which registered pinia persisted state and inside the node_modules/pinia-persistedstate/dist/nuxt.mjs

As you can see, nuxt.mjs doesn't get called in server side

nuxt.mjs calls the createPersistedState in this case.

However, if i use createPersistedState directly in the nuxt plugin like so
<img width="994" alt="image" src="https://user-images.githubusercontent.com/3810177/183247626-03bf271a-cc2f-4104-b71b-31a23aa0162e.png">

You'll see that getItem is also being called in server side, which restores the state and makes everything available in a middleware or any server side script

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/3810177/183247678-561f10c5-ae0e-4f91-9228-c20144c0e7e6.png">

**Comment by prazdevs** [comment] 2022-08-07 17:33
If the issue is from the nuxt-cookie, maybe we should see if there's an issue in their repo and look for a fix over there ? or at least be sure it is meant to behave taht way

**Comment by stephenjason89** [comment] 2022-08-08 03:25
@prazdevs  it's a different issue not related to nuxt cookie

**Comment by prazdevs** [comment] 2022-11-26 01:25
v3 is now release with available nuxt module as well! docs are also deployed 🚀 
closing this for now, if still having issues, feel free to reopen

**Closed by prazdevs** 2022-11-26 01:25 UTC
Labels: 🔍️ pending triage
