### ISSUE TITLE
would you like to support store2 through factory function

### ISSUE THREAD

**Issue by wxhccc** [prazdevs/pinia-plugin-persistedstate#82] opened 2022-07-05 07:14 UTC
I had use store2 in my application. it can simply use namespace and save plain object.

I think this library is a more convenient way to implement some core functions of this plugin, is any chance to suport this package through factory function?

thank you for listening

**Comment by wxhccc** [comment] 2022-07-05 07:29
here is mine simple persist plugin，I hope you can easier understand my demand because my english is not good. I wish someday i can use pinia-plugin-persistedstate in my app，come on !!

```
export type CheckStateProp = (store: PiniaPluginContext['store']) => boolean

export type PropPath<K extends string> = K | [K, CheckStateProp]

export interface StoragePluginOptions<S> {
  defaultCore?: 'local' | 'session'
  localPaths?: PropPath<Extract<keyof S, string>>[]
  sessionPaths?: PropPath<Extract<keyof S, string>>[]
}

export const storagePlugin = (contenxt: PiniaPluginContext) => {
  const { store, options } = contenxt
  const { storage } = options
  if (!storage) {
    return
  }
  const { defaultCore = 'local', localPaths, sessionPaths } = storage
  const storeKey = `store-${store.$id}`

  const handleKeys = (keys?: PropPath<string>[]) => {
    return keys
      ? keys.reduce<string[]>((acc, cur) => {
          if (typeof cur === 'string') {
            acc.push(cur)
          } else if (Array.isArray(cur) && cur.length === 2 && cur[1](store)) {
            acc.push(cur[0])
          }
          return acc
        }, [])
      : undefined
  }
  const restoreStateValue = () => {
    const localValue = Storage.get(storeKey)
    const sessionValue = Storage.session(storeKey)
    store.$patch({ ...localValue, ...sessionValue })
  }
  restoreStateValue()
  const storeStateValue = (state: StateTree) => {
    if (localPaths?.length === 0 && sessionPaths?.length === 0) {
      return
    }
    const keys = {
      local: handleKeys(localPaths),
      session: handleKeys(sessionPaths)
    }
    const values = {
      local: {} as StateTree,
      session: {} as StateTree
    }
    Object.keys(state).forEach((key) => {
      const value = toRaw(state[key])
      if (value instanceof Function) {
        return
      }
      if (keys.local?.includes(key) && defaultCore === 'session') {
        values.local[key] = value
      } else if (keys.session?.includes(key) && defaultCore === 'local') {
        value.session[key] = value
      } else if (keys[defaultCore]) {
        if (keys[defaultCore]?.includes(key)) {
          values[defaultCore][key] = value
        }
      } else {
        values[defaultCore][key] = value
      }
    })
    ;(['local', 'session'] as (keyof typeof values)[]).forEach((key) => {
      if (Object.keys(values[key]).length) {
        Storage[key](storeKey, values[key])
      }
    })
  }
  store.$subscribe((_mutation, state) => storeStateValue(state), { detached: true })
}
```

**Comment by prazdevs** [comment] 2022-07-05 07:48
are you trying to use store2 directly ? or you want to have more configurable store, and have different storages for different paths ? :)

**Comment by prazdevs** [comment] 2022-07-19 23:44
I think we could think of it for the V2 of the plugin, i'm working on it :)

**Comment by wxhccc** [comment] 2022-07-27 07:54
> I think we could think of it for the V2 of the plugin, i'm working on it :)

thank you.

**Comment by prazdevs** [comment] 2022-07-27 10:41
V2 will allow you to specify multiple persistences so you could do smth like

```ts
defineStore('store', {
  state: () => ({
    toLocal: '',
    toSession: '',
  }),
  persist: [
    {
      paths: ['toLocal'],
      storage: localStorage,
    },
    {
      paths: ['toSession'],
      storage: sessionStorage,
    },
  ],
})
```

That allows you to store things in separate storages. Would that solve your problem ?

**Comment by wxhccc** [comment] 2022-07-28 01:51
> V2 will allow you to specify multiple persistences so you could do smth like
> 
> ```ts
> defineStore('store', {
>   state: () => ({
>     toLocal: '',
>     toSession: '',
>   }),
>   persist: [
>     {
>       paths: ['toLocal'],
>       storage: localStorage,
>     },
>     {
>       paths: ['toSession'],
>       storage: sessionStorage,
>     },
>   ],
> })
> ```
> 
> That allows you to store things in separate storages. In this example above, the `toLocal` value will be persisted in localStorage while the `toSession` value will be persisted in sessionStorage.
> 
> Would that solve your problem ?

in fact to store things in separate storages is requirement of  #19 , I need function such as `['pathA', ['pathB', (state) => stats.pathA === true]]` , and a third storage package support namespace to store values.
And i think you method to separate storages is good.

**Comment by prazdevs** [comment] 2022-08-02 10:10
closing this as what is left is now a duplicate of #76 

if i am missing on something, feel free to reopen this and explain what i'm missing! 😄

**Closed by prazdevs** 2022-08-02 10:10 UTC
Labels: ❓ question
