### ISSUE TITLE
Update state on Window storage event

### ISSUE THREAD

**Issue by dominik-korsa** [prazdevs/pinia-plugin-persistedstate#55] opened 2022-03-30 16:17 UTC
Feature idea: listen to the `storage` event (https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event) and automatically reload state. This would prevent desynchronization when our app is opened in more than one tab or when local storage is modified using devtools

**Comment by prazdevs** [comment] 2022-04-09 18:01
Hey :) 
I like the idea of allowing  sync. The issue is that it only works with localStorage. So that would mean tying a feature to only one specific storage. However, if you want to have it working with the plugin, you can use the hooks for it in your store definition. Here's a working configuration example :

```ts
import { defineStore } from 'pinia'

export const useUserStore = defineStore('user', {
  state: () => ({
    username: 'PraZ',
  }),
  persist: {
    afterRestore: ctx => {
      window.addEventListener('storage', ({ newValue }) => {
        ctx.store.$patch(JSON.parse(newValue as string))
      })
    }
  }
})
```

**Comment by prazdevs** [comment] 2022-04-14 08:24
Closing this for now, feel free to reopen if you have any comment regarding the idea :)

**Closed by prazdevs** 2022-04-14 08:24 UTC
