### ISSUE TITLE
[core] persisting `reactive` objects

### ISSUE THREAD

**Issue by capoia** [prazdevs/pinia-plugin-persistedstate#120] opened 2022-09-26 14:45 UTC
### Describe the bug

First, I would like to thank you for the package, it helps me a lot.

I have the following problem:
When I have an object using reactive() in the store and I update it, the store is not persisted, unfortunately **I couldn't create any replay environment, because it involves cookies and stackblitz doesn't use cookies, so it's never persisted.**

But follow video showing the behavior and the code can be seen on stackblitz .

https://user-images.githubusercontent.com/21159928/192306810-0634e028-bfd8-4984-b980-59e174def033.mp4

### Reproduction

https://stackblitz.com/edit/github-ukyz4d?file=store/auth.ts

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 110.05 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment] 2022-09-27 08:33
i think it's a duplicate of #108 ? i still have to look into that 😦

**Comment by capoia** [comment] 2022-09-27 21:33
> i think it's a duplicate of #108 ? i still have to look into that 😦

@prazdevs yeah, I also think! I ended up solving it using zipson! maybe it's something in the native serialize/deserialize method you guys use.

**Comment by prazdevs** [comment] 2022-09-27 22:11
I'll need to take a look at how pinia handles reactive objects vs refs. the serialization process might change the structure of the `reactive` losing persistence. thanks for the input. 

As a workaround for using reactive for now, if using zipson works, we'll keep that. Hopefully we may find a proper solution.

**Comment by capoia** [comment] 2022-11-24 13:47
I have a problem with persistence again if it is reactive.
Not even zipson is working now!
If you have any object using reactive() the entire store is not persisted.

**Comment by prazdevs** [comment] 2022-11-26 01:31
persisting reactive objects should work with latest version and the nuxt module in a nuxt context :)
tested it right now, if you still have issues with it, feel free to reopen

**Closed by prazdevs** 2022-11-26 01:31 UTC
Labels: 🐛 bug, 🪛 workaround
