### ISSUE TITLE
When there is object type data in the state, the persistence fails

### ISSUE THREAD

**Issue by KahrLu** [prazdevs/pinia-plugin-persistedstate#58] opened 2022-04-27 07:57 UTC
Hi @prazdevs , I use Nuxt3 rc-1 & pinia & pinia-plugin-presistedstate in my project.
I found that when the fields in state has least one object type (multiple layers), the persistence fails.
for example: state.cartInfo is a Object type value.
![image](https://user-images.githubusercontent.com/76502123/165470525-31909e78-61c4-4b63-97d1-5cf3ebabfd80.png)

I don't know if this is caused by your plugin or usecookie in Nuxt3.
besides, Could you give more examples on using localStorage in Nuxt3, when I make the value of config key "storage" as window.localStorage or localStorage, it throw a undefined error

**Comment by 7flash** [comment] 2022-04-27 17:05
The same issue, not working with an array

**Comment by 7flash** [comment] 2022-04-27 19:19
Another issue though, it's not accessible on API route

**Comment by prazdevs** [comment] 2022-04-28 09:32
Hi :) I'll take a look at the nuxt3-rc1 issue ASAP. 

As for now, if you want to use localStorage with Nuxt, you have to declare the persistedstate plugin as client only since localStorage is a browser-only API. This is done by calling your file `persistedstate.client.ts`. The `.client.ts` part runs the plugin only on client side.

**Comment by prazdevs** [comment] 2022-05-08 01:25
I tried to reproduce it but could not have the same bug. Can you provide a proper repo to reproduce the issue ? thanks

**Comment by prazdevs** [comment] 2022-05-17 23:19
I'm starting to think it was linked to #64 and should be fixed now. Feel free to reopen if the problem still exists!

**Closed by prazdevs** 2022-05-17 23:19 UTC
Labels: bug

**Comment by prazdevs** [comment] 2022-05-31 11:08
I should document it somewhere maybe.
