### ISSUE TITLE
[core] Add excluded paths option

### ISSUE THREAD

**Issue by bisubus** [prazdevs/pinia-plugin-persistedstate#109] opened 2022-08-20 11:20 UTC
### Clear and concise description of the problem

The suggestion is to add an option to exclude paths. This allows for more fine-grained persistence without requiring to change store structure:

```js
persist: [{
  key: 'foo-unsecure',
  paths: ['foo'],
  excludedPaths: ['foo.bar', 'foo.baz'],
  storage: localStorage
}, {
  key: 'foo',
  paths: ['foo.bar', 'foo.baz'],
  storage: sessionStorage
}]
```

### Suggested solution

```
            let toStore = state;

            if (paths?.length) {
              toStore = pick(toStore, ...paths);
            }

            if (excludedPaths?.length) {
              toStore = omit(toStore, ...excludedPaths);
            }
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment] 2022-09-01 13:02
Hi, this is a fairly easy enhancement that can be considered! I'll try to do it asap :)

**Comment by marktlinn** [comment] 2023-05-27 22:33
Happy to do this, if the issue is still open for assignment?

**Comment by prazdevs** [comment] 2023-05-27 23:13
Hi @marktlinn it still is, the requirements are to use no external libraries, and keep the code as small and readable as possible 😄

**Comment by havok2063** [comment] 2024-08-15 23:16
Any update on this?  This would be incredibly useful for me as well!

**Comment by prazdevs** [comment] 2024-09-04 22:02
released in v4

**Closed by prazdevs** 2024-09-04 22:02 UTC
Labels: ✨ enhancement
