### ISSUE TITLE
[nuxt] Nuxt ssr cookie limit 4096bytes . Need a bigger alternative.

### ISSUE THREAD

**Issue by stephenjason89** [prazdevs/pinia-plugin-persistedstate#84] opened 2022-07-12 19:23 UTC
Hello, are there other alternatives to cookie?
I have a bigger store which needs to persist and it is more than 4096bytes

**Comment by prazdevs** [comment] 2022-07-13 07:39
So far, i can only think of browser storages like localStorage, but it is client only. Do you need the SSR full compatibility ?

**Comment by prazdevs** [comment] 2022-07-19 23:43
I could only think of splitting the store into multiple cookies, cause i dont see many alternatives compatible with both client and server side 🤔

**Comment by prazdevs** [comment] 2022-07-20 09:37
I dont know what data structure you store in Pinia, but if you have unsplittable properties/chunks heavier than 4KB, I dont think they belong in the store. Maybe some cached database middleware or something would be more appropriate ?

**Comment by ASoldo** [comment] 2022-07-20 09:57
@stephenjason89 can you give more info about data you're storing. It's used for what purpose? I'm curious.

**Comment by stephenjason89** [comment] 2022-07-20 10:14
@ASoldo After I login, i get back all this info and I am storing 
```
    user:{
       branches:[{id:1, name:'warehouse']
       roles:[ {name: 'Admin', permissions: ['many', 'different' , 'permissions']} ]         -> this can be a lot specially if you are an admin
       permissions:['specific','user','permissions']        
    }
    token: 'Bearer token lkjalksjdlkjasldjlasdkajlsdjlajsdajsd',
    tokenExpiration: date,
    refreshToken: date,
    refreshTokenExpiration: 'Bearer token lkjalksjdlkjasldjlasdkajlsdjlajsdajsd',
    ```
    
    This is so i don't need to query what permissions the user have.
    
    I use it here because I need this info to customize the page being rendered in the server side depending on the users permissions
    
@prazdevs Would you mind giving me samples on some cached database middleware?

**Comment by FrancoLab** [comment] 2022-09-01 12:20
Any update on this thread. I am facing the same problem

**Comment by FrancoLab** [comment] 2022-09-01 13:13
Thanks @prazdevs, is there a way to use the plugin to store multiple cookies. ie A cookie with a specific key per store that you set up. Mine does not even persist all my stores. Only one of them.

**Comment by prazdevs** [comment] 2022-09-01 13:18
Technically it should, but I need to look into when the cookie and keys are parsed and created, that could explain your problem.

**Comment by FrancoLab** [comment] 2022-09-01 13:24
Here is my Nuxt3 Plugin:

```
// plugins/persistedstate.js
import { createNuxtPersistedState } from "pinia-plugin-persistedstate/nuxt";
import { useCookie } from "#app"; // optional import as Nuxt will auto-import it

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.$pinia.use(createNuxtPersistedState(useCookie));
});
```

My Store

```
import {defineStore} from 'pinia'
import axios from 'axios'

const baseUrl = url;

export const useGlobalConfigStore = defineStore('globalConfig', {
	state: () => ({
		config: null,
		fxRates: null,
		locales: null,
		error: null,
        count: 0,
        countGlobal: 0,
        countFx: 0,
        countLang: 0,
	}),
	actions: {
		async getConfig() {
            let header = {
                "Accept": "application/json",
                "Accept-Language": "en",
                Authorization: "Bearer token",
            }

			let reqOptions = {
				url: url,
				method: "GET",
				headers: header,
			}

			await axios
				.request(reqOptions)
				.then((response) => {
					if (response.status === 200) {
						this.config = response.data.result.data;
						this.error = null;
					} else {
						console.log({response});
					}
                    this.countGlobal = this.countGlobal + 1;
				})
				.catch((error) => {
					this.error = error;
				})

		},

		async getCurrencyConfig() {
            let header = {
                "Accept": "application/json",
                "Accept-Language": "en",
                Authorization: "Bearer token",
            }

			let reqOptions = {
				url: url,
				method: "GET",
				headers: header,
			}

			await axios
				.request(reqOptions)
				.then((response) => {
					if (response.status === 200) {
						this.fxRates = response.data.result.data;
						this.error = null;
					} else {
						console.log({response});
					}
                    this.countFx = this.countFx + 1;
				})
				.catch((error) => {
					this.error = error;
				})
		},

		async getLocaleConfig() {
            let header = {
                "Accept": "application/json",
                "Accept-Language": "en",
                Authorization: "Bearer token",
            }

			let reqOptions = {
				url: url,
				method: "GET",
				headers: header,
			}

			await axios
				.request(reqOptions)
				.then((response) => {
					if (response.status === 200) {
						this.locales = response.data.result.data;
						this.error = null;
					} else {
						console.log({response});
					}
                    this.countLang = this.countLang + 1;
				})
				.catch((error) => {
					this.error = error;
				})
		}
	},
	persist: {
        key: "globalStore",
    },
})
```

**Comment by FrancoLab** [comment] 2022-09-01 13:25
The problem I am facing is that it only persists one of my stores. This one in the example above does not persist.

**Comment by prazdevs** [comment] 2022-09-01 23:37
You may want to open another issue with a proper reproduction repo/stackblitz to make it clearer, it's moving away from the main concern of this issue :)

**Comment by prazdevs** [comment] 2022-11-13 21:24
As the solution proposed in #99 works, you can use it to create your own storage deriving nuxt's useCookie (or any sort of cookie) and pass it to the plugin. 
Closing this issue as the split will not be implemented since out of scope, but it has a workaround.

**Closed by prazdevs** 2022-11-13 21:24 UTC
Labels: ✋ help wanted
