### ISSUE TITLE
Usage with Nuxt3 (SSR)

### ISSUE THREAD

**Issue by cyanerd** [prazdevs/pinia-plugin-persistedstate#8] opened 2022-01-06 07:42 UTC
Hello! Thanks for great package. My problem:
1. Nuxt 3, vue 3, pinia 2.0
2. Create plugin, code:

```
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate';
import {NuxtApp} from 'nuxt3';

export default function ({$pinia, ssrContext}: NuxtApp) {
  $pinia.use(piniaPluginPersistedstate);
}
```

3. Then I create build (ssr enabled) and then start server, I get this error:

```
extender is not a function
  at file://./server/node_modules/pinia/dist/pinia.mjs:1556:43
```
4. This block of code in pinia.mjs:
```
// apply all plugins
pinia._p.forEach((extender) => {
  assign(store, scope.run(() => extender({
      store,
      app: pinia._a,
      pinia,
      options: optionsForPlugin,
  })));
})
```

How should i use package correctly with nuxt3 ssr?

**Comment by prazdevs** [comment] 2022-01-06 11:26
Hi, thanks for using it! I haven't looked much into Nuxt 3 much, I was waiting for it to go out of beta, but I'll try to have a look at it when I have some time.

**Comment by prazdevs** [comment] 2022-01-15 21:11
Hey @cyanerd  , could you provide a repo with the error so I can start looking into it  ? I have a lot of stuff to do atm, and that'd help a lot.

**Comment by prazdevs** [comment] 2022-01-21 14:03
Okay I investigated a bit and managed to make it work. You can add it through a Nuxt3 client-only plugin. To do so, as explained in the docs, create a file under the `plugins/` folder and give it a name ending in `.client.ts`.

I created a file name `pinia-persistedstate.client.ts` which contained the following : 
```ts
import PiniaPluginPersistedstate from 'pinia-plugin-persistedstate'
import { defineNuxtPlugin } from '#app'

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.$pinia.use(PiniaPluginPersistedstate)
})
```

and it worked fine. Automatic typings from nuxt are actually insane!

I will try to look for an easier way to implement it and eventually publish a nuxt package for the plugin when i have some time and more infos on Nuxt3. Hope it helps.

**Comment by sasial-dev** [comment] 2022-02-09 06:33
> Okay I investigated a bit and managed to make it work. You can add it through a Nuxt3 client-only plugin. To do so, as explained in the docs, create a file under the `plugins/` folder and give it a name ending in `.client.ts`.
> 
> I created a file name `pinia-persistedstate.client.ts` which contained the following :
> 
> ```ts
> import PiniaPluginPersistedstate from 'pinia-plugin-persistedstate'
> import { defineNuxtPlugin } from '#app'
> 
> export default defineNuxtPlugin(nuxtApp => {
>   nuxtApp.$pinia.use(PiniaPluginPersistedstate)
> })
> ```
> 
> and it worked fine. Automatic typings from nuxt are actually insane!
> 
> I will try to look for an easier way to implement it and eventually publish a nuxt package for the plugin when i have some time and more infos on Nuxt3. Hope it helps.
> 
> EDIT: there might be more to that than just using it client side only, I guess there may be solutions for server-side by not using localStorage and client only APIs. I'm just not good enough with SSR (yet) to give a proper answer. I'm open to any kind of help regarding this! :)

Do you have a repro/codesandbox so I can reproduce it working? I've setup the plugin but it isn't working...

**Comment by prazdevs** [comment] 2022-02-09 19:56
Hey, here's a repo with an example I had working locally.

https://github.com/prazdevs/nuxt3-pinia-persistedstate-example

**Comment by madsh93** [comment] 2022-02-10 10:39
Yes, the solution works for client, which I think is still very useful. Wrapping components in <ClientOnly> fixes the hydration errors. 

@prazdevs vuex persisted state uses cookie to work on server side. https://github.com/robinvdvleuten/vuex-persistedstate#readme  - Nuxt3 has a SSR Friendly cookie composable, could this be used?
https://v3.nuxtjs.org/docs/usage/cookies/

**Comment by prazdevs** [comment] 2022-02-10 10:53
> Yes, the solution works for client, which I think is still very useful. Wrapping components in `ClientOnly` fixes the hydration errors.
> 
> @prazdevs vuex persisted state uses cookie to work on server side. https://github.com/robinvdvleuten/vuex-persistedstate#readme - Nuxt3 has a SSR Friendly cookie composable, could this be used? https://v3.nuxtjs.org/docs/usage/cookies/

Ok that's very interesting, maybe this could be subject to a proper Nuxt module to integrate the pinia plugin easily with configuration ? I'll try to look into it when I get some time. If anyone is up to work on it, feel free to do so ^_^

**Comment by prazdevs** [comment] 2022-02-10 19:30
Ok here's a working store definition using Nuxt's `useCookie`:

```ts
import { defineStore } from 'pinia';

export const useUserStore = defineStore('user', {
  state: () => ({
    token: 'fake'
  }),
  persist: {
    storage: {
      getItem: (key) => { return useCookie(key, { encode: x => x, decode: x => x }).value },
      setItem: (key, value) => { useCookie(key, { encode: x => x, decode: x => x }).value = value },
      removeItem: (key) => { useCookie(key, { encode: x => x, decode: x => x }).value = null },
    }
  },
})
```

**Comment by prazdevs** [comment] 2022-02-10 22:13
Okay, I documented the use with Nuxt with the Cookies API. I'll close the issue for now. I still consider making a Nuxt module at some point hopefully before Nuxt leaves the beta state.
Thanks for helping and suggesting the convenient APIS ! :)

**Closed by prazdevs** 2022-02-10 22:13 UTC
Labels: help wanted, question

**Comment by sasaorasanin** [comment] 2022-04-09 01:41
@prazdevs Nuxt3 is throwing that store cannot be accessed. Cookies are not stored..

**Comment by prazdevs** [comment] 2022-04-09 01:51
> @prazdevs Nuxt3 is throwing that store cannot be accessed. Cookies are not stored..

are you using the latest method and nuxt-specific factory function recommended in the docs/readme? if so and it is still not working, feel free to open a proper issue :)

**Comment by sasaorasanin** [comment] 2022-04-09 02:57
@prazdevs It was not set up because my state was bigger than 4096 bytes. It works fine 👍
